<#setting classic_compatible=true>
    <!DOCTYPE html>
    <html>
    <head>
        <meta charset="UTF-8">
        <title>统计</title>
        <link rel="stylesheet" href="../css/bootstrap.min.css">
        <script src="../js/jquery-3.3.1.min.js"></script>
        <script src="../js/loserStarJsUtils.js"></script>
        <script src="../js/ajaxUtils.js" type="text/javascript"></script>
        <script src="../ftl/oreData/js/statistics.js" type="text/javascript"></script>
    </head>

    <body>
        <table class="table table-condensed table-striped table-bordered">
            <tr>
                <td>日期</td>
                <td>单位</td>
                <td>干量</td>
                <td>湿量</td>
                <td>水份（%）</td>
                <td>平均水份</td>
                <td>Fe</td>
                <td>平均Fe</td>
                <td>S</td>
                <td>平均S</td>
                <td>P</td>
                <td>平均P</td>
                <td>Pb</td>
                <td>平均Pb</td>
                <td>As</td>
                <td>平均As</td>
                <td>Sio2</td>
                <td>平均Sio2</td>
                <td>Tio2</td>
                <td>平均Tio2</td>
                <td>Zn</td>
                <td>平均Zn</td>
                <td>Cu</td>
                <td>平均Cu</td>
                <td>Sn</td>
                <td>平均Sn</td>
                <td>K20</td>
                <td>平均K20</td>
                <td>Na20</td>
                <td>平均Na20</td>
                <td>单价</td>
                <td>平均单价</td>
            </tr>
            <#list list as sub>
            <tr>
                    <td>${sub.date?string("yyyy-MM-dd")}</td>
                    <td>${sub.unit}</td>
                    <td>${sub.ganliang}</td>
                    <td>${sub.wet_count}</td>
                    <td>${sub.water_count}</td>
                    <td>${sub.avgWater}</td>
                    <td>${sub.fe}</td>
                    <td>${sub.avgFe}</td>
                    <td>${sub.s}</td>
                    <td>${sub.avgS}</td>
                    <td>${sub.p}</td>
                    <td>${sub.avgP}</td>
                    <td>${sub.pb}</td>
                    <td>${sub.avgPb}</td>
                    <td>${sub.as}</td>
                    <td>${sub.avgAs}</td>
                    <td>${sub.sio2}</td>
                    <td>${sub.avgSio2}</td>
                    <td>${sub.tio2}</td>
                    <td>${sub.avgTio2}</td>
                    <td>${sub.zn}</td>
                    <td>${sub.avgZn}</td>
                    <td>${sub.cu}</td>
                    <td>${sub.avgCu}</td>
                    <td>${sub.sn}</td>
                    <td>${sub.avgSn}</td>
                    <td>${sub.k20}</td>
                    <td>${sub.avgK20}</td>
                    <td>${sub.na20}</td>
                    <td>${sub.avgNa20}</td>
                    <td>${sub.price}</td>
                    <td>${sub.avgPrice}</td>
            </tr>
            </#list>
        </table>
        <div>小计：</div>
		<table class="table table-condensed table-striped table-bordered">
            <tr>
                <td>干量（总和）：</td>
                <td>${sumGanliang}</td>
            </tr>
            <tr>
                <td>湿量（总和）：</td>
                <td>${sum_wet_count}</td>
            </tr>
            <tr>
                <td>平均水份（总和）：</td>
                <td>${sum_avgWater}</td>
            </tr>
            <tr>
                <td>综合水份：</td>
                <td>${synthetical_water_count}</td>
            </tr>
            <tr>
                <td>平均Fe（总和）：</td>
                <td>${sum_avgFe}</td>
            </tr>
            <tr>
                <td>综合Fe：</td>
                <td>${synthetical_Fe}</td>
            </tr>
            <tr>
                <td>平均S（综合）：</td>
                <td>${sum_avgS}</td>
            </tr>
            <tr>
                <td>综合S：</td>
                <td>${synthetical_S}</td>
            </tr>
            <tr>
                <td>平均P（总和）：</td>
                <td>${sum_avgP}</td>
            </tr>
            <tr>
                <td>综合P：</td>
                <td>${synthetical_P}</td>
            </tr>
            <tr>
                <td>平均Pb（总和）：</td>
                <td>${sum_avgPb}</td>
            </tr>
            <tr>
                <td>综合Pb：</td>
                <td>${synthetical_Pb}</td>
            </tr>
            <tr>
                <td>平均As（总和）：</td>
                <td>${sum_avgAs}</td>
            </tr>
            <tr>
                <td>综合As：</td>
                <td>${synthetical_As}</td>
            </tr>
            <tr>
                <td>平均Sio2（总和）：</td>
                <td>${sum_avgSio2}</td>
            </tr>
            <tr>
                <td>综合Sio2：</td>
                <td>${synthetical_Sio2}</td>
            </tr>
            <tr>
                <td>平均Tio2（总和）：</td>
                <td>${sum_avgTio2}</td>
            </tr>
            <tr>
                <td>综合Tio2：</td>
                <td>${synthetical_Tio2}</td>
            </tr>
            <tr>
                <td>平均Zn（总和）：</td>
                <td>${sum_avgZn}</td>
            </tr>
            <tr>
                <td>综合Zn：</td>
                <td>${synthetical_Zn}</td>
            </tr>
            <tr>
                <td>平均Cu（总和）：</td>
                <td>${sum_avgCu}</td>
            </tr>
            <tr>
                <td>综合Cu：</td>
                <td>${synthetical_Cu}</td>
            </tr>
            <tr>
                <td>平均Sn（总和）：</td>
                <td>${sum_avgSn}</td>
            </tr>
            <tr>
                <td>综合Sn：</td>
                <td>${synthetical_Sn}</td>
            </tr>
            <tr>
                <td>平均K20（总和）：</td>
                <td>${sum_avgK20}</td>
            </tr>
            <tr>
                <td>综合K20：</td>
                <td>${synthetical_K20}</td>
            </tr>
            <tr>
                <td>平均Na20（总和）：</td>
                <td>${sum_avgNa20}</td>
            </tr>
            <tr>
                <td>综合Na20：</td>
                <td>${synthetical_Na20}</td>
            </tr>
            <tr>
                <td>平均单价（总和）：</td>
                <td>${sum_avgPrice}</td>
            </tr>
            <tr>
                <td>综合单价：</td>
                <td>${synthetical_price}</td>
            </tr>
        </table>
    </body>

    </html>